Fixed. can not install bundler v2
https://circleci.com/gh/sue445/index_shotgun/457

```
+ gem install bundler --no-document
Fetching: bundler-2.0.0.gem (100%)
ERROR:  Error installing bundler:
	The last version of bundler (>= 0) to support your Ruby & RubyGems was 1.17.3. Try installing it with `gem install bundler -v 1.17.3`
	bundler requires RubyGems version >= 3.0.0. The current RubyGems version is 2.7.6. Try 'gem update --system' to update RubyGems itself.
```