Use latest ruby
https://circleci.com/gh/sue445/index_shotgun/468

```
+ gem update --system --no-document
Updating rubygems-update
Fetching: rubygems-update-3.0.2.gem (100%)
ERROR:  Error installing rubygems-update:
	rubygems-update requires Ruby version >= 2.3.0.
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ dir_chdir - /usr/local/bundle/gems/rubygems-update-2.6.12
Exited with code 1
```